name: FlitsFiets
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports: # Should not be exposed and done through the internal network with discovery. Exposed here for development purposes only.
      - "5672:5672"
      - "15672:15672"   # UI
    environment:
      RABBITMQ_DEFAULT_USER: app
      RABBITMQ_DEFAULT_PASS: secret
    networks: [ internal ]
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddydata:/data
      - caddyconfig:/config
    networks: [ edge, internal ]
    profiles: [ prod ]

#  keycloak:
#    container_name: baeldung-keycloak.openid-provider
#    image: quay.io/keycloak/keycloak:25.0.1
#    command:
#      - start-dev
#      - --import-realm
#    ports:
#      - 8080:8080
#    volumes:
#      - ./keycloak/:/opt/keycloak/data/import/
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#      KC_HTTP_PORT: 8080
#      KC_HOSTNAME_URL: http://localhost:8080
#      KC_HOSTNAME_ADMIN_URL: http://localhost:8080
#      KC_HOSTNAME_STRICT_BACKCHANNEL: true
#      KC_HTTP_RELATIVE_PATH: /
#      KC_HTTP_ENABLED: true
#      KC_HEALTH_ENABLED: true
#      KC_METRICS_ENABLED: true
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    healthcheck:
#      test: [ 'CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:8080/auth/health/live' ]
#      interval: 5s
#      timeout: 5s
#      retries: 20


  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - '5000:80'
      # Change the number before : to the port the SMTP server should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - '25:25'
      # Change the number before : to the port the IMAP server should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - '143:143'
      # Change the number before : to the port the POP3 server should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
    #      - '110:110'
    volumes:
      # This is where smtp4dev stores the database...
      - smtp4dev-data:/smtp4dev
    networks: [ internal ]
    environment:
      #Specifies the URLs the web UI will use inside the container.
      - ServerOptions__Urls=http://*:80
      #Specifies the server hostname. Used in auto-generated TLS certificate if enabled.
      - ServerOptions__HostName=smtp4dev
      #Specifies the port the IMAP server will listen on - allows standard email clients to view/retrieve messages
      #"ServerOptions__ImapPort"=143
      #Specifies the port the POP3 server will listen on - allows standard email clients to retrieve/delete messages
      #"ServerOptions__Pop3Port"=110
      #Specifies POP3 TLS mode (None, StartTls, ImplicitTls) and whether secure connection is required
      #"ServerOptions__Pop3TlsMode"=StartTls
      #"ServerOptions__Pop3SecureConnectionRequired"=false
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80']
  #    healthcheck:
  #      test: ["CMD-SHELL", "wget -qO- http://localhost/ || exit 1"]
  #      interval: 5s
  #      timeout: 3s
  #      retries: 12
  #      start_period: 10s
    profiles: [ dev ]


  service-onboarding:
    image: 'ff-onboarding:latest'
    restart: unless-stopped
    networks: [ edge, internal ]
    profiles: [ prod ]

  service-frontend:
    image: 'ff-frontend:latest'
    restart: unless-stopped
    networks: [ edge, internal ]
    profiles: [ prod ]

  service-users:
    image: 'ff-users:latest'
#    depends_on:
#      postgres:
#        condition: service_started
    restart: unless-stopped
    networks: [ internal ]
    profiles: [ prod ]

  service-appointments:
    image: 'ff-appointments:latest'
    #    depends_on:
    #      postgres:
    #        condition: service_started
    restart: unless-stopped
    networks: [ internal ]
    profiles: [ prod ]

  service-mailing:
    image: 'ff-mailing:latest'
    #    depends_on:
    #      postgres:
    #        condition: service_started
    restart: unless-stopped
    networks: [ internal ]
    profiles: [ prod ]

networks:
  internal:
    external: false
    driver: bridge
  edge:
    external: false
    driver: bridge

volumes:
#  pgdata:
  caddydata:
  caddyconfig:
  smtp4dev-data:
