spring:
  application:
    name: Mailing
  rabbitmq:
    host: localhost
    port: 5672
    username: app
    password: secret
  datasource:
    url: jdbc:h2:file:./data/db;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  mail:
    host: ${SMTP_HOST:smtp4dev}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:admin}
    password: ${SMTP_PASSWORD:admin}
    senderMail: "BikeFlash <info@flitsfiets.nl>"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 6002
